// <auto-generated />
using System;
using CollegeProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CollegeProject.Migrations
{
    [DbContext(typeof(CollegeDBContext))]
    [Migration("20240518140754_UpdateModifyStudentSchema")]
    partial class UpdateModifyStudentSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CollegeProject.Data.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<string>("Address")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StudentID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentID = 1,
                            Address = "India",
                            DOB = new DateTime(2008, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "india@gmail.com",
                            StudentName = "Sample1"
                        },
                        new
                        {
                            StudentID = 2,
                            Address = "USA",
                            DOB = new DateTime(2012, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "usa@gmail.com",
                            StudentName = "Sample2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
